version: 2
jobs:
    install+build:
        docker:
            - image: circleci/node:10-browsers-legacy
        steps:
            - checkout
            - restore_cache: # special step to restore the dependency cache
                  key: dependency-cache-{{ checksum "package.json" }}
            - run: npm ci
            - save_cache: # special step to save the dependency cache
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
    lint:
        docker:
            - image: circleci/node:10-browsers-legacy
        steps:
            - checkout
            - restore_cache: # special step to restore the dependency cache
                  key: dependency-cache-{{ checksum "package.json" }}
            - run: npm ci
            - save_cache: # special step to save the dependency cache
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run: npm run lint
    format:
        docker:
            - image: circleci/node:10-browsers-legacy
        steps:
            - checkout
            - restore_cache: # special step to restore the dependency cache
                  key: dependency-cache-{{ checksum "package.json" }}
            - run: npm ci
            - save_cache: # special step to save the dependency cache
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run: npm run format:check
    unit-tests:
        docker:
            - image: circleci/node:10-browsers-legacy
        steps:
            - checkout
            - restore_cache: # special step to restore the dependency cache
                  key: dependency-cache-{{ checksum "package.json" }}
            - run: npm ci
            - save_cache: # special step to save the dependency cache
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run: npm run test
    integration-tests:
        docker:
            - image: circleci/node:10-browsers-legacy
        steps:
            - checkout
            - restore_cache: # special step to restore the dependency cache
                  key: dependency-cache-{{ checksum "package.json" }}
            - run: npm ci
            - save_cache: # special step to save the dependency cache
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run: npm run test:integration
    player-e2e-test:
        docker:
            - image: circleci/node:10-browsers-legacy
        steps:
            - checkout
            - restore_cache: # special step to restore the dependency cache
                  key: dependency-cache-{{ checksum "package.json" }}
            - run: npm ci
            - save_cache: # special step to save the dependency cache
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run: npm run test:e2e:player
    release:
        docker:
            - image: 'circleci/node:latest'
        steps:
            - checkout
            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            - run:
                  name: install
                  command: npm install
            - run:
                  name: release
                  command: npm run semantic-release || true
workflows:
    version: 2
    h5peditor:
        jobs:
            - install+build
            - lint
            - format
            - unit-tests
            - player-e2e-test
            - integration-tests
            - release:
                  requires:
                      - install+build
                      - lint
                      - format
                      - unit-tests
                      - player-e2e-test
                      - integration-tests
